### ISSUE TITLE
make it package

### ISSUE THREAD

**Issue by mimoubelhadj16** [SalehTZ/playable_side_menu#1]
please can you make it a package it helps a lot

**Comment by SalehTZ** [comment]
Good idea 💡. I'll be working on it soon. There are some bugs that need to be fixed first.

**Comment by mimoubelhadj16** [comment]
thank you appreciate your efforts 👌🏻

**Comment by SalehTZ** [comment]
This project is a package now 🥳🎉.
You can find it on [github](https://github.com/SalehTZ/playable_toolbar_flutter) and [pub.dev](https://pub.dev/packages/playable_toolbar_flutter).
Thank you for your issue.
If you find any problems using this package, please let me know.
Also, you can find me on [Instagram](https://www.instagram.com/mr_tz.dev/). Feel free to contact me anytime.
